project1/project1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('walpapir/', include('walpapir.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


project1/walpapir/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings

from . import views
from django.urls import path

from django.conf.urls.static import static

app_name = 'walpapir'

urlpatterns = [
    #debug urls
    path('user_d', views.user_d, name='user_d'),
    path('redeem_d', views.redeem_d, name="redeem_d"),
    path('userEdit_d', views.userEdit_d, name="userEdit_d"),
    path('userCreateComplete_d', views.userCreateComplete_d, name="userCreateComplete_d"),

    path('home/', views.home, name='home'),
    path('desktop/', views.desktop, name='desktop'),
    path('mobile/', views.mobile, name='mobile'),
    #userpage and several other pages needs some updates
    path('howToUse/', views.how2use, name='how2use'),
    path('prehome/', views.prehome, name='prehome'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('prehome/', views.prehome, name='prehome'),
    path('postpage/', views.page4post, name='page4post'),
    path('postdone/', views.postDone, name='postdone'),
    path('signup/', views.UserCreate.as_view(), name='signUp'),
    path('signup/done', views.UserCreateDone.as_view(), name='signup_done'),
    path('signup/complete/<token>/', views.UserCreateComplete.as_view(), name='signup_complete'),
    path('search/',views.search,name='search'),
    path('ajax/',views.ajax,name="ajax"),
    #path('registarUserName', views.registarUserName, name="HNRegister"),

    #user pages
    path('user/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
    path('user_edit/<int:pk>', views.UserUpdate.as_view(), name='user_update'),

    #imageView
    path('image/<int:pk>', views.ImageView.as_view(), name='image_view'),
    path('image_u/<int:pk>', views.ImageView_u.as_view(), name='image_view_u'),

    #style Filter
    path('style', views.style_transfer, name='style'),
    path('profile',views.profile,name='profile'),
    path('profile<int:pk>', views.Profile_View.as_view(), name='profile_s')
]

project1/walpapir/models.py
from django.db import models
# Create your models here.
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
import os.path

class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin, models.Model):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    handle_name = models.CharField(max_length = 20, blank=True)
    bio = models.CharField(blank=True, default='bio', max_length=300)

    #point has user point.
    point = models.IntegerField(default=0)
    #pointCount exists only for making sure the validity of how the point was gained.
    pointCount = models.IntegerField(default=0)

    profilepicture = models.ImageField(upload_to="profile_image",default=os.path.join("profile_image","180x120.jpeg"))

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            #'Designates whether the user can log into this admin site.'),
            'aaa',
            )
        )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'aaa'
            #'Designates whether this user should be treated as active. '
            #'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        handle_nameを返す
        """
        return self.handle_name

from datetime import datetime

class Photo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='walpapir_image')#ファイルの名前
    title = models.CharField(max_length=30)
    time = models.DateTimeField(default=datetime.now)#自分で時間を設定する場合はdefaultはいらない。
    mode = models.NullBooleanField()#0:DESKTOP  1:MOBILE

class Style(models.Model):
    image = models.ImageField(upload_to='walpapir_style')
    title = models.CharField(max_length=20)

project1/walpapir/views.py
#For registration
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest,HttpResponse,HttpResponseRedirect
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm
)
from django.urls import reverse
from django.shortcuts import render, get_object_or_404

import os
import os.path

from .models import User, Photo, Style



#プロジェクトで使用しているUserモデルを取得
User = get_user_model()
# Create your views here.


def home(request):
    homePhoto = Photo.objects.all()

    return render(request, 'walpapir/home1.html', {
        'photo':homePhoto,
    })

def mobile(request):
    mobilePhoto = Photo.objects.all()

    return render(request, 'walpapir/mobile.html', {
        'photo':mobilePhoto,
    })

def desktop(request):
    desktopPhoto = Photo.objects.all()

    return render(request, 'walpapir/desktop.html', {
        'photo':desktopPhoto,
    })

def how2use(request):
    return render(request, 'walpapir/how2use.html')

def prehome(request):
    return render(request, 'walpapir/prehome.html')

def page4post(request):

    #ログインしてないと入れない
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('walpapir:login'))

    if request.method=='GET':
        return render(request,'walpapir/page4Post.html')

    image=request.FILES['image']
    title=request.POST['title']
    mode=request.POST['radio']

    request.user.photo_set.create(image=image,title=title,mode=mode)

    return HttpResponseRedirect(reverse('walpapir:postdone'))#次に表示させるページの名前

def postDone(request):
    return render(request, 'walpapir/postDone.html')

#They are debug functions.

def user_d(request):
    user_photo = User.photo_set.all()
    return render(request, 'walpapir/user_d', {
        'photo': user_photo,
    })


def redeem_d(request):
    return render(request, 'walpapir/page4Redeem.html')

def userEdit_d(request):
    if request.method=="GET":
        return render(request, 'walpapir/userEdit_d.html')

    user_id =request.POST["id"]
    user=User.objects.get(id=user_id)

    if "image" in request.FILES:
        if user.profilepicture.name != "profile_image/180x120.jpeg":
            a=os.path.join(settings.MEDIA_ROOT,user.profilepicture.name)
            os.remove(a)

        user.profilepicture=request.FILES["image"]
        user.save()

    user_photo = Photo.objects.all()

    return render(request, 'walpapir/userPage.html', {
        'photo': user_photo,

    })

def userCreateComplete_d(request):
    return render(request, 'walpapir/user_create_complete_d.html')

#=========================

class Top(generic.TemplateView):
    template_name = 'walpapir/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'walpapir/page4Login.html'

class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'walpapir/top.html'

class UserCreate(generic.CreateView):
    """ユーザー仮登録"""

    template_name = 'walpapir/page4register.html' #ユーザー登録のためのページ
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('walpapir/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('walpapir/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('walpapir:signup_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'walpapir/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'walpapir/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

"""def registarUserName(request):
    lists = request.POST
    handle_name = lists["handle_name"]

    User.handle_name = handle_name

    return render(request, 'walpapir/user_create_done.html')
"""

photo=Photo.objects.all()
img=16
search=""
page_last=0

def search(request):
    global photo,img,search,page_last
    lists=request.GET
    search,page,select=lists["search"],int(lists["page"]),lists["select"]
    photo=Photo.objects.all()

    if(select=="0"):
        photo=photo.order_by("-time")
    elif(select=="1"):
        photo=photo.order_by("time")

    if search=="":
        page_last=int(photo.count()/img)+1
        return render(request,'walpapir/searchResults.html',{
            'photo':photo[0+(img*(page-1)):img+(img*(page-1))],
            'page':page,
            'search':search,
            'page_last':page_last,
            'count':photo.count(),
            'select':int(select),
        })

    j=search.split()

    for s in j:
        photo=photo.filter(title__contains=s)

    page_last=int(photo.count()/img)+1

    return render(request,'walpapir/searchResults.html',{
        'photo':photo[0+(img*(page-1)):img+(img*(page-1))],
        'page':page,
        'search':search,
        'page_last':page_last,
        'count':photo.count(),
    })

def ajax(request):
    global photo,img,search,page_last
    page=int(request.GET["page"])
    return HttpResponse(render(request,'walpapir/image.html',{'photo':photo[0+(img*(page-1)):img+(img*(page-1))],}))

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuer

class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'walpapir/userPage.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'walpapir/userEdit_d.html'

    def get_success_url(self):
        return resolve_url('userPage', pk=self.kwargs['pk'])


class ImageView(generic.TemplateView):
    template_name = 'walpapir/imageView.html'

    def get_context_data(self, **kwargs):

        context = super(ImageView, self).get_context_data(**kwargs)
        photo=Photo.objects.all()
        style=Style.objects.all()

        try:
            context['prev'] = photo.filter(id__lt=self.kwargs.get('pk')).order_by("-id")[0].id
        except:
            context['prev'] = -1

        context['photo'] = photo.get(id=self.kwargs.get('pk'))
        context['style'] = style

        try:
            context['next'] = photo.filter(id__gt=self.kwargs.get('pk'))[0].id
        except:
            context['next'] = -1
        return context

class ImageView_u(generic.TemplateView):
    template_name = 'walpapir/imageView.html'

    def get_context_data(self, **kwargs):

        context = super(ImageView_u, self).get_context_data(**kwargs)
        photo_now = Photo.objects.get(id=self.kwargs.get('pk'))
        photo=photo_now.user.photo_set.all()
        style=Style.objects.all()

        try:
            context['prev'] = photo.filter(id__lt=self.kwargs.get('pk')).order_by("-id")[0].id
        except:
            context['prev'] = -1

        context['photo'] = photo_now
        context['style'] = style
        try:
            context['next'] = photo.filter(id__gt=self.kwargs.get('pk'))[0].id
        except:
            context['next'] = -1
        return context

def style_transfer(request):

    if request.method=='GET':
        return render(request, 'walpapir/style.html')

    image = request.FILES['image']
    title = request.POST['title']

    request.user.photo_set.create(image=image, title=title)

    return HttpResponseRedirect(reverse('walpapir/style.html'))

def profile(request):
    user_id = request.POST['user']

    return render(request,'walpapir/profile.html',{
        "usr":User.objects.get(id=user_id),
    })

class Profile_View(generic.TemplateView):
    template_name = 'walpapir/userPage.html'

    def get_context_data(self, **kwargs):


project1/walpapir/templates/walpapir/homeTemplate.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %}homeTemplate{% endblock %}
    </title>

    {% block basicLinks %}

    <script src="{% static 'walpapir/jQuery/3-3-1.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'walpapir/CSS/menustyle.css' %}" />
    <script type="text/javascript" src="{% static 'walpapir/js/FixNavigation.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous" />

    {% endblock %}

    <style>
    {% if user.is_authenticated %}

      .hamburgerMenuItem, .hamburgerMenuOpenButton {
        background-color: #00B6F3;
      }

      .hamburgerMenuOpen {
        background-color: #00B6F3;
      }

    {% endif %}

    {% block style %}
    {% endblock %}
    </style>

    {% block additionalLinks %}
    {% endblock %}

  </head>
  <body>
    {% block headerBox %}

    <div id="headerBox">

      <a href="{% url 'walpapir:prehome' %}"><div id="logo"></div></a>
      <div id="logoWord">WalPapir</div>
      {% if not user.is_authenticated %}
      <a class="signUpButton" href="{% url 'walpapir:signUp' %}">Sign&nbsp;&nbsp;up</a>
      {% endif %}
      <div id="menuIcon">
      <script>
        $(function(){});
          $(window).on('load resize', function(){
            if(window.innerWidth >= 801){
              document.getElementById('logo').innerHTML = '<img src="{% static "walpapir/UI/logo_60x60.png" %}" id="menuIcon" />';
            } else {
              document.getElementById('logo').innerHTML = '<img src="{% static "walpapir/UI/logo_40x40.png" %}" id="menuIcon" />';
            }
          })
      </script>
    </div>
    </div>

    <form action="{% url 'walpapir:search'%}" method="GET">
      <input type="text" class="search" placeholder="Search..." name="search">
      <input type="hidden" name="page" value="1">
      <input type="hidden" name="select" value="0">
      <button type="submit" class="searchButton"><i class="fas fa-search"></i></button>
    </form>

    {% endblock %}

    {% block navigationBar %}

    <!-- navigation bar -->
      <ul class="menu">
        <li><a href="{% url 'walpapir:home' %}">
          HOME</a></li>

      <li><a href="{% url 'walpapir:desktop' %}">
          DESKTOP</a></li>

      <li><a href="{% url 'walpapir:mobile' %}">
          MOBILE</a></li>

      {% if user.is_authenticated %}
      <li><a href="{% url 'walpapir:user_detail' user.pk %}">
          USER</a></li>
      {% else %}
      <li><a href="{% url 'walpapir:login' %}">
        Sign in</a></li>
      {% endif %}
      <li class="slider"></li>

    </ul>
    <!-- navigation bar -->

    {% endblock %}

    {% block hamburgerMenu %}

    <!-- hamburgerMenu -->

    <nav class="hamburgerMenu">
      <input type="checkbox" href="#" class="hamburgerMenuOpen" name="hamburgerMenuOpen" id="hamburgerMenuOpen" />
      <label class="hamburgerMenuOpenButton" for="hamburgerMenuOpen">
        <span class="hamburger hamburger1"></span>
        <span class="hamburger hamburger2"></span>
        <span class="hamburger hamburger3"></span>
      </label>

      <a href="{% url 'walpapir:how2use' %}" class="hamburgerMenuItem"><i class="fas fa-question"></i></a>
      <a href="{% url 'walpapir:page4post' %}" class="hamburgerMenuItem"><i class="fas fa-paper-plane"></i></a>
      <a href="./favPage.html" class="hamburgerMenuItem"><i class="fa fa-heart"></i></a>
      <a href="mailto:papillonp@icloud.com" class="hamburgerMenuItem"><i class="fa fa-envelope"></i></a>

    </nav>

    <!-- filters -->
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
        <defs>
          <filter id="shadowed-goo">

              <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
              <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
              <feGaussianBlur in="goo" stdDeviation="3" result="shadow" />
              <feColorMatrix in="shadow" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 -0.2" result="shadow" />
              <feOffset in="shadow" dx="1" dy="1" result="shadow" />
              <feComposite in2="shadow" in="goo" result="goo" />
              <feComposite in2="goo" in="SourceGraphic" result="mix" />

          </filter>
          <filter id="goo">

              <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
              <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
              <feComposite in2="goo" in="SourceGraphic" result="mix" />

          </filter>
        </defs>
    </svg>

    <!-- filters -->

    <!-- hamburgerMenu -->
    {% endblock %}

    
    {% block mainContent %}

    {% endblock %}

    <br>
    <br>

    {% block footer %}

    <script>
    $(function(){
      $(".scrollToTopButton").click(function() {
        $("body, html").animate({scrollTop: 0}, 300, 'linear');
      });
    });

    $(function(){
      var height = $(document).height()+15;
      $(".footer").css("top",height+"px");
    })
    </script>

    <div class="footer">

      <div class="footer-left">
        About WalPapir<br>
        <a href="{% url 'walpapir:prehome' %}">Overview</a><br>
        <a href="{% url 'walpapir:how2use' %}">How to use?</a><br>
        <a href="#">Contact us</a><br>
      </div>

      <div class="scrollToTopButton">
        <div style="position:absolute;top:50%;left:50%;font-size:31px;transform:translate(-50%, -55%);-webkit-transform:translate(-50%,-55%);">
          <i class="fas fa-angle-double-up"></i>
        </div>
      </div>

      <div class="footer-right">
        Social Media<br>
      </div>

    </div>
    {% endblock %}



  </body>

</html>

project1/walpapir/templates/walpapir/imageView.html
{% extends './homeTemplate.html' %}
{% load static %}

{% block title %}ImageView{% endblock %}

{% block style %}

a.active{
  background-color: #3498db;
  pointer-events: none;
}

li.slider{
  width: 25%;
  height: 100%;
  position: absolute;
  left: 0;
  top: 0;
  background-color: #3498db;
  z-index: 8;
  transition: left 0.4s, background-color 0.4s;
}

#left-content {
  border-radius: 12px;
  font-family: "Roboto Slab", sans-serif;
  width: 80%;
  position: absolute;
  left: 6%;
  top: 170px;
  background-image:  url("{% static 'walpapir/UI/paper.png' %}");
  text-align: center;
  padding-bottom: 70px;
}

#right-content {
  width: 15%;
  position: absolute;
  right: 6%;
  top: 250px;
  background-image: url("{% static 'walpapir/UI/paper.png' %}");
  border-radius: 12px;

  display: none;
}

#wrap {
  margin-bottom: 50px;
}

body {
  padding-bottom: 70px;
}

#scale{
  background: url("{%static 'walpapir/UI/scale.png'%}");
  position: absolute;
  display:block;
  width:100%;
  height:100%;
  margin:2px;
}
.profile{
  border-radius: 50%;
  width:  50px;
  height: 50px;
  margin:5px 10px;
  float:left;
}

{% endblock %}

{% block additionalLinks %}

<link rel="stylesheet" href="{% static 'walpapir/CSS/ImageView.css' %}">
<script type="text/javascript" src="{% static 'walpapir/js/downloadButton.js' %}"></script>

<script type="text/javascript">

  //Filter of fast-style-transfer
  $(function styleFilter(){
    $(".styleFilter").mouseover(function(){
      $(this).find("img").css("border","solid 2px blue");
      $(this).find("div").css("display", "inline");
    }).mouseout(function(){
      $(this).find("img").css("border", "solid 2px black");
      $(this).find("div").css("display", "none");
    })
  })

  $(function(){
    var wid;
    if($(window).width()>800){
      wid = $(window).width()*0.6;
    }else{
      wid = $(window).width()*0.88;
    }
    var fil = Math.floor(wid/200);
    fil = Math.floor(100/fil);
    fil = fil + "%";
    $(".image_fild").css("width", fil);

    $(window).resize(function(){
      var wid;
      if($(window).width()>800){
        wid = $(window).width()*0.6;
      }else{
        wid = $(window).width()*0.88;
      }
      var fil = Math.floor(wid/200);
      fil = Math.floor(100/fil);
      fil = fil + "%";
      $(".image_fild").css("width", fil);
    })
  })

  $(function(){
  $(".image").mouseover(function(){
    $(this).find("img").css("border","solid 2px blue");
    $(this).find("div").css("display","inline");
  }).mouseout(function(){
    $(this).find("img").css("border","solid 2px black");
    $(this).find("div").css("display","none");
  })
})

</script>
{% endblock %}

{% block mainContent %}

      <div id="left-content">
        <br>
        {% if prev != -1 %}
        <a href="{% url 'walpapir:image_view' prev %}">
        <div id="previousButton">
          <i class="fas fa-caret-left"></i>
        </div>
        </a>
        {% endif %}

        {% if next != -1 %}
        <a href="{% url 'walpapir:image_view' next %}">
        <div id="nextButton">
          <i class="fas fa-caret-right"></i>
        </div>
        </a>
        {% endif %}

        <div style="font-size:40px;"><p align="center">{{photo.title}}</p></div>
        <hr style="border: 0.5px solid #ccc">
        <br><br><br>

        <img src="{{photo.image.url}}" style="border:solid 1px black">
        <br><br><br>
        <div class="downloadButton">
          <a href="{{photo.image.url}}">
            <i class="fas fa-download"></i>
          </a>
        </div>


        <hr style="border: 0.5px solid #ccc">
        <div style="width:100%;height: 60px;">
          <div style="width:50%;float: left;">
              <!--ハートはダウンロードのアイコン-->
          </div>

          <div style="width:45%;float:right;">
              <!--
              <form action="{%url 'walpapir:profile'%}" method="POST">
                {% csrf_token %} -->
                <a href="{% url 'walpapir:profile_s' photo.user.pk %}">
                <input type="image" value="{{photo.user.id}}" name="user" src="{{photo.user.profilepicture.url}}" class="profile" onmousedown="return false;">
              <!-- </form> --></a>
            <span style="margin:20px 0px;float:left;font-size: 20px;">{{photo.user.email}}</span><!--名前にする-->
          </div>
        </div>
        <hr style="border: 0.5px solid #ccc">


        {% for st in style %}

        <div align="center" style="float:left;" class="image_fild">
          <div style="position:relative;margin:5px;width:190px;background:white;" class="image">
            <span id="scale"></span>
           <img src="{{st.image.url}}" style="width: 190px;height: 190px;border:solid 2px black;" alt="{{st.title}}" oncontextmenu="return false;">
            <div style="position:absolute;width:190px;background-color:rgba(0,0,0,0.7);bottom:6px;left:2px;display:none;" class="text">
              <span style="color:white;" >{{st.title}}</span>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>

      <div id="right-content">
        <br><br>
      </div>

{% endblock %}